### ISSUE TITLE
Trademark use

### ISSUE THREAD

**Issue by stripthis** [lenforiee/Amnesia#1]
Hello, 

I'm a passbolt maintainer, first of all great project! :) 

I just wanted to flag that the trademark use, is not in line with the official guidelines. Please have a look at the guidelines for use of trademark (logo and name): https://www.passbolt.com/credits/trademark-guidelines

Since this project is not affiliated with passbolt, we kindly request you to remove the logo from your application. This is to avoid confusing users between official and non-official applications.

With regards to the names, the guideline is to use "x for passbolt" and not "passbolt x" to also show that this is not an official project directly in the name.

Thank you for your understanding. Feel free to reach out to us if you have any questions :).

**Comment by lenforiee** [comment]
Hello,

Thanks for interest in project! 
I have replaced the passbolt logos with custom made for the app, I also improved the use of passbolt trademark in ac3cc1e this commit and lastly I've changed the repo name to not interfere with passbolt use of trademark

Once again thanks for interest, if you find anything that needs to be improved/changed please let me know!
